import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Calendar, Download, Trophy, TrendingDown } from 'lucide-react';
import { monitoringAPI } from '../services/monitoringAPI';
import jsPDF from 'jspdf';
import './DailySummary.css';

function DailySummary() {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState(null);
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);
  const [fromDate, setFromDate] = useState(() => {
    const date = new Date();
    date.setDate(date.getDate() - 7);
    return date.toISOString().split('T')[0];
  });
  const [toDate, setToDate] = useState(new Date().toISOString().split('T')[0]);
  const [error, setError] = useState('');
  const [showDownloadModal, setShowDownloadModal] = useState(false);
  const [showDateRangeModal, setShowDateRangeModal] = useState(false);

  useEffect(() => {
    fetchSummary();
  }, [selectedDate]);

  const fetchSummary = async () => {
    try {
      setLoading(true);
      setError('');
      const result = await monitoringAPI.getDailySummary(selectedDate);
      setData(result);
    } catch (err) {
      console.error('Error fetching daily summary:', err);
      setError(err.message || 'Failed to load daily summary');
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = () => {
    if (!data) return;
    
    // Create PDF
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    let yPos = margin;
    
    // Title
    doc.setFontSize(20);
    doc.setFont(undefined, 'bold');
    doc.text('Daily Farm Summary', pageWidth / 2, yPos, { align: 'center' });
    yPos += 10;
    
    // Date
    doc.setFontSize(14);
    doc.setFont(undefined, 'normal');
    const dateStr = (() => {
      const [year, month, day] = data.date.split('-').map(Number);
      const date = new Date(year, month - 1, day);
      return date.toLocaleDateString('en-US', { 
        weekday: 'long', 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
      });
    })();
    doc.text(dateStr, pageWidth / 2, yPos, { align: 'center' });
    yPos += 20;
    
    // Line
    doc.setLineWidth(0.5);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 15;
    
    // Statistics
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text('Statistics', margin, yPos);
    yPos += 10;
    
    doc.setFont(undefined, 'normal');
    doc.text(`Total Feed: ${data.totalFeed.toFixed(1)} kg`, margin, yPos);
    yPos += 8;
    doc.text(`Total Milk: ${data.totalMilk.toFixed(1)} L`, margin, yPos);
    yPos += 8;
    const ratio = data.totalFeed > 0 ? (data.totalMilk / data.totalFeed).toFixed(2) : '0.00';
    doc.text(`Yield-to-Feed Ratio: ${ratio} L/kg`, margin, yPos);
    yPos += 15;
    
    // Performance
    doc.setFont(undefined, 'bold');
    doc.text('Performance', margin, yPos);
    yPos += 10;
    
    doc.setFont(undefined, 'normal');
    doc.text(`Best Performing Cow: ${data.bestCowId || 'N/A'}`, margin, yPos);
    yPos += 8;
    doc.text(`Lowest Performing Cow: ${data.lowestCowId || 'N/A'}`, margin, yPos);
    yPos += 15;
    
    // Footer
    doc.setFontSize(10);
    doc.setFont(undefined, 'italic');
    doc.text('Generated by DairySense', pageWidth / 2, pageHeight - 10, { align: 'center' });
    
    // Save PDF
    doc.save(`daily-summary-${data.date}.pdf`);
    setShowDownloadModal(false);
  };

  const handleDownloadDateRange = async () => {
    try {
      // Fetch data for date range
      const reports = [];
      const start = new Date(fromDate);
      const end = new Date(toDate);
      
      for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
        try {
          const dateStr = d.toISOString().split('T')[0];
          const result = await monitoringAPI.getDailySummary(dateStr);
          reports.push({ date: dateStr, ...result });
        } catch (err) {
          console.error(`Error fetching data for ${d.toISOString().split('T')[0]}:`, err);
        }
      }

      if (reports.length === 0) {
        alert('No data available for the selected date range');
        return;
      }

      // Create PDF
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      let yPos = margin;

      // Title
      doc.setFontSize(20);
      doc.setFont(undefined, 'bold');
      doc.text('Date Range Farm Summary Report', pageWidth / 2, yPos, { align: 'center' });
      yPos += 10;

      // Date Range
      doc.setFontSize(12);
      doc.setFont(undefined, 'normal');
      const fromStr = new Date(fromDate).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
      const toStr = new Date(toDate).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
      doc.text(`${fromStr} to ${toStr}`, pageWidth / 2, yPos, { align: 'center' });
      yPos += 15;

      // Summary for each day
      reports.forEach((report, index) => {
        if (yPos > pageHeight - 40) {
          doc.addPage();
          yPos = margin;
        }

        doc.setFontSize(14);
        doc.setFont(undefined, 'bold');
        const reportDate = new Date(report.date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
        doc.text(reportDate, margin, yPos);
        yPos += 8;

        doc.setFontSize(10);
        doc.setFont(undefined, 'normal');
        doc.text(`Feed: ${report.totalFeed.toFixed(1)} kg | Milk: ${report.totalMilk.toFixed(1)} L | Ratio: ${report.totalFeed > 0 ? (report.totalMilk / report.totalFeed).toFixed(2) : '0.00'} L/kg`, margin, yPos);
        yPos += 6;
        doc.text(`Best: ${report.bestCowId || 'N/A'} | Lowest: ${report.lowestCowId || 'N/A'}`, margin, yPos);
        yPos += 10;

        if (index < reports.length - 1) {
          doc.setLineWidth(0.2);
          doc.line(margin, yPos, pageWidth - margin, yPos);
          yPos += 8;
        }
      });

      // Footer
      doc.setFontSize(10);
      doc.setFont(undefined, 'italic');
      doc.text('Generated by DairySense', pageWidth / 2, pageHeight - 10, { align: 'center' });

      // Save PDF
      doc.save(`farm-summary-${fromDate}-to-${toDate}.pdf`);
    } catch (error) {
      console.error('Error generating date range report:', error);
      alert('Failed to generate date range report. Please try again.');
    }
  };

  if (loading) {
    return (
      <div className="daily-summary">
        <div className="loading-container">
          <div className="loading-spinner">
            <div className="loading-dot"></div>
            <div className="loading-dot"></div>
            <div className="loading-dot"></div>
          </div>
          <p>Loading summary...</p>
        </div>
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="daily-summary">
        <header className="summary-header">
          <button 
            className="back-button" 
            onClick={() => navigate(-1)}
          >
            <ArrowLeft size={20} />
            <span>Back</span>
          </button>
          <h1>Daily Report</h1>
        </header>
        <div className="error-container">
          <p>{error || 'Summary not available'}</p>
          <button onClick={fetchSummary}>Retry</button>
        </div>
      </div>
    );
  }

  const yieldFeedRatio = data.totalFeed > 0 
    ? (data.totalMilk / data.totalFeed).toFixed(2)
    : '0.00';

  return (
    <div className="daily-summary">
      <header className="summary-header">
        <button 
          className="back-button" 
          onClick={() => navigate('/monitoring')}
        >
          <ArrowLeft size={20} />
          <span>Back</span>
        </button>
        <h1>Daily Report</h1>
        <div className="date-selector">
          <Calendar size={18} />
          <input 
            type="date" 
            value={selectedDate}
            onChange={(e) => setSelectedDate(e.target.value)}
            className="date-input"
          />
        </div>
      </header>

      <div className="summary-content">
        <div className="summary-date-banner">
          <Calendar size={20} />
          <span>{(() => {
            // Parse date string properly to avoid timezone issues
            const [year, month, day] = data.date.split('-').map(Number);
            const date = new Date(year, month - 1, day);
            return date.toLocaleDateString('en-US', { 
              weekday: 'long', 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            });
          })()}</span>
        </div>

        <div className="summary-stats-grid">
          <div className="summary-stat-card">
            <h3>Total Feed</h3>
            <p className="summary-stat-value">{data.totalFeed.toFixed(1)}</p>
            <span className="summary-stat-unit">kg</span>
          </div>

          <div className="summary-stat-card">
            <h3>Total Milk</h3>
            <p className="summary-stat-value">{data.totalMilk.toFixed(1)}</p>
            <span className="summary-stat-unit">liters</span>
          </div>

          <div className="summary-stat-card highlight">
            <h3>Yield-to-Feed Ratio</h3>
            <p className="summary-stat-value">{yieldFeedRatio}</p>
            <span className="summary-stat-unit">L/kg</span>
          </div>
        </div>

        <div className="performance-section">
          <div className="performance-card best">
            <div className="performance-icon">
              <Trophy size={24} />
            </div>
            <div className="performance-content">
              <h3>Best Performing Cow</h3>
              <p className="performance-id">{data.bestCowId || 'N/A'}</p>
            </div>
          </div>

          <div className="performance-card lowest">
            <div className="performance-icon">
              <TrendingDown size={24} />
            </div>
            <div className="performance-content">
              <h3>Lowest Performing Cow</h3>
              <p className="performance-id">{data.lowestCowId || 'N/A'}</p>
            </div>
          </div>
        </div>

        <div className="download-section">
          <button className="download-btn" onClick={() => setShowDownloadModal(true)}>
            <Download size={20} />
            <span>Download Today's Report</span>
          </button>
        </div>

        {/* Date Range Download Section */}
        <div className="date-range-download-section">
          <h3>Download Date Range Report</h3>
          <div className="date-range-inputs">
            <div className="date-input-group">
              <label>
                <Calendar size={16} />
                <span>From Date</span>
              </label>
              <input 
                type="date" 
                value={fromDate}
                onChange={(e) => setFromDate(e.target.value)}
                className="date-input"
              />
            </div>
            <div className="date-input-group">
              <label>
                <Calendar size={16} />
                <span>To Date</span>
              </label>
              <input 
                type="date" 
                value={toDate}
                onChange={(e) => setToDate(e.target.value)}
                className="date-input"
              />
            </div>
            <button 
              className="download-range-btn" 
              onClick={() => setShowDateRangeModal(true)}
              disabled={!fromDate || !toDate || new Date(fromDate) > new Date(toDate)}
            >
              <Download size={18} />
              <span>Download Range Report</span>
            </button>
          </div>
        </div>
      </div>

      {/* Date Range Download Modal */}
      {showDateRangeModal && (
        <div className="modal-overlay" onClick={() => setShowDateRangeModal(false)}>
          <div className="download-modal" onClick={(e) => e.stopPropagation()}>
            <h3>Download Date Range Report</h3>
            <div className="download-preview">
              <p><strong>From:</strong> {new Date(fromDate).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
              <p><strong>To:</strong> {new Date(toDate).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
              <p className="modal-note">This will generate a PDF report for the selected date range.</p>
            </div>
            <div className="modal-actions">
              <button className="cancel-btn" onClick={() => setShowDateRangeModal(false)}>
                Cancel
              </button>
              <button 
                className="confirm-download-btn" 
                onClick={() => {
                  // TODO: Implement date range report download
                  handleDownloadDateRange();
                  setShowDateRangeModal(false);
                }}
              >
                <Download size={18} />
                Download PDF
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Download Confirmation Modal */}
      {showDownloadModal && (
        <div className="modal-overlay" onClick={() => setShowDownloadModal(false)}>
          <div className="download-modal" onClick={(e) => e.stopPropagation()}>
            <h3>Download Daily Report</h3>
            <div className="download-preview">
              <p><strong>Date:</strong> {(() => {
                const [year, month, day] = data.date.split('-').map(Number);
                const date = new Date(year, month - 1, day);
                return date.toLocaleDateString('en-US', { 
                  year: 'numeric', 
                  month: 'long', 
                  day: 'numeric' 
                });
              })()}</p>
              <p><strong>Total Feed:</strong> {data.totalFeed.toFixed(1)} kg</p>
              <p><strong>Total Milk:</strong> {data.totalMilk.toFixed(1)} L</p>
              <p><strong>Yield-to-Feed Ratio:</strong> {data.totalFeed > 0 ? (data.totalMilk / data.totalFeed).toFixed(2) : '0.00'}</p>
              <p><strong>Best Cow:</strong> {data.bestCowId || 'N/A'}</p>
              <p><strong>Lowest Cow:</strong> {data.lowestCowId || 'N/A'}</p>
            </div>
            <div className="modal-actions">
              <button className="cancel-btn" onClick={() => setShowDownloadModal(false)}>
                Cancel
              </button>
              <button className="confirm-download-btn" onClick={handleDownload}>
                <Download size={18} />
                Download
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default DailySummary;

